openapi: 3.0.0
info:
  title: Eligibility Verification API
  version: 1.0.0
paths:
  /verify:
    post:
      summary: Verify patient eligibility
      operationId: verifyEligibility
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                carrier_name:
                  type: string
                member_id:
                  type: string
                full_name:
                  type: string
                dob:
                  type: string
                  format: date
              required:
                - carrier_name
                - member_id
                - full_name
                - dob
      responses:
        '200':
          description: Eligibility verification result
          content:
            application/json:
              schema:
                type: object
                properties:
                  eligible:
                    type: boolean
                    description: Indicates if the patient is eligible (true) or not (false)
                  message:
                    type: string
                    description: Additional information or reason if the patient is not eligible
        '400':
          description: Invalid input
        '500':
          description: Server error