# generated by fastapi-codegen:
#   filename:  eligibility_api.yaml
#   timestamp: 2024-09-09T22:15:15+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import VerifyPostRequest, VerifyPostResponse

app = FastAPI(
    title='Eligibility Verification API',
    version='1.0.0',
)


@app.post('/verify', response_model=VerifyPostResponse)
def verify_eligibility(body: VerifyPostRequest) -> VerifyPostResponse:
    """
    Verify patient eligibility
    """
    pass
