# generated by fastapi-codegen:
#   filename:  /Users/lorenamesa/Workspace/interview_prep/eligibility_api.yaml
#   timestamp: 2024-09-09T22:15:15+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import BaseModel, Field


class VerifyPostRequest(BaseModel):
    carrier_name: str
    member_id: str
    full_name: str
    dob: date


class VerifyPostResponse(BaseModel):
    eligible: Optional[bool] = Field(
        None, description='Indicates if the patient is eligible (true) or not (false)'
    )
    message: Optional[str] = Field(
        None,
        description='Additional information or reason if the patient is not eligible',
    )
