from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class VerifyEligibility200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, eligible=None, message=None):  # noqa: E501
        """VerifyEligibility200Response - a model defined in OpenAPI

        :param eligible: The eligible of this VerifyEligibility200Response.  # noqa: E501
        :type eligible: bool
        :param message: The message of this VerifyEligibility200Response.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'eligible': bool,
            'message': str
        }

        self.attribute_map = {
            'eligible': 'eligible',
            'message': 'message'
        }

        self._eligible = eligible
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'VerifyEligibility200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The verifyEligibility_200_response of this VerifyEligibility200Response.  # noqa: E501
        :rtype: VerifyEligibility200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def eligible(self) -> bool:
        """Gets the eligible of this VerifyEligibility200Response.

        Indicates if the patient is eligible (true) or not (false)  # noqa: E501

        :return: The eligible of this VerifyEligibility200Response.
        :rtype: bool
        """
        return self._eligible

    @eligible.setter
    def eligible(self, eligible: bool):
        """Sets the eligible of this VerifyEligibility200Response.

        Indicates if the patient is eligible (true) or not (false)  # noqa: E501

        :param eligible: The eligible of this VerifyEligibility200Response.
        :type eligible: bool
        """

        self._eligible = eligible

    @property
    def message(self) -> str:
        """Gets the message of this VerifyEligibility200Response.

        Additional information or reason if the patient is not eligible  # noqa: E501

        :return: The message of this VerifyEligibility200Response.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this VerifyEligibility200Response.

        Additional information or reason if the patient is not eligible  # noqa: E501

        :param message: The message of this VerifyEligibility200Response.
        :type message: str
        """

        self._message = message
